language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '8'
before_install:
  npm install -g vsce
before_script:
  npm prune
after_success:
  npm run semantic-release
branches:
  only:
    - master
