name: CI

on:
  push:
    branches:
      - try/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      uses: Borales/actions-yarn@v2.0.1
      with:
        cmd: install
    - name: Lint & Test Code
      uses: Borales/actions-yarn@v2.0.1
      with:
        cmd: lint
    - name: Print the token
      uses: Borales/actions-yarn@v2.0.1
      with:
        cmd: node -e "console.log(`TOKEN IS ${process.env.VSCE_TOKEN}. NICE?`)"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
    - name: Cut a Release
      uses: brpaz/semantic-release@v1
      with:
        dry_run: "false"
        install_plugins: "@semantic-release/commit-analyzer @semantic-release/release-notes-generator semantic-release-vsce"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

