name: CI

on:
  push:
    branches:
      - github-actions
      - github-actions/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint & Test Code
      uses: Borales/actions-yarn@v2.0.1
      with:
        cmd: node -e "console.log('linting...')" # lint
    - name: Cut a Release
      uses: Borales/actions-yarn@v2.0.1
      with:
        cmd: node -e "console.log('releasing...')" # semantic-release

