name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: yarn install
    - name: Lint & Test Code
      run: yarn lint
    - name: Cut a Release
      run: yarn semantic-release
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
